#if !defined(AFX_MCD_H__95CF9D09_DAF3_4392_B9CD_AD2C83CAF8CF__INCLUDED_)
#define AFX_MCD_H__95CF9D09_DAF3_4392_B9CD_AD2C83CAF8CF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMcd wrapper class

class CMcd : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMcd)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x32d4e900, 0x934a, 0x43ff, { 0x92, 0xf2, 0xcc, 0xcf, 0x10, 0x2e, 0x53, 0x97 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetDirection();
	void SetDirection(BOOL);

// Operations
public:
	void SetNumbers(long x, long y);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MCD_H__95CF9D09_DAF3_4392_B9CD_AD2C83CAF8CF__INCLUDED_)
